#!/usr/bin/env bash
# This script displays /etc/passwd info in a custom format
while IFS=: read -r username password uid gid uid_info home shell; do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $uid_info"
done < /etc/passwd
